name: Daily Financial Report

on:
  schedule:
    - cron: '0 7 * * *'  # Run at 7:00 AM UTC daily (adjust as needed)
  workflow_dispatch:  # Allows you to manually trigger the workflow
  push:
    branches:
      - main  # Trigger on pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # You can specify your required Python version

    - name: Cache Python dependencies
      uses: actions/cache@v3  # Use the latest version
      with:
        path: ~/.cache/pip  # Cache directory for pip
        key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}  # Cache key based on requirements.txt hash
        restore-keys: |
          ${{ runner.os }}-python-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies

    - name: Run the script
      run: python main.py
